# Generated by Django 5.0 on 2023-12-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_adminuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
    ]
