# Generated by Django 5.0 on 2023-12-26 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_adminuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
    ]
