# Generated by Django 5.0 on 2023-12-27 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_email_adminuser_admin_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin user'),
        ),
    ]
