# Generated by Django 5.0 on 2023-12-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_product_category_id_producttype_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='is_active',
        ),
    ]
