# Generated by Django 5.0 on 2023-12-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.media', verbose_name='pictures'),
        ),
    ]
