# Generated by Django 5.0 on 2023-12-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_media_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='brand_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='inventory.brand', verbose_name='brand id'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, null=True, verbose_name='recommended price'),
        ),
    ]
