# Generated by Django 5.0 on 2023-12-24 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_productinventory_product_id_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='upc',
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True, help_text='format:true=product visible', verbose_name='Location availability'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='inventory.product', verbose_name='product id'),
        ),
    ]
