# Generated by Django 5.0 on 2023-12-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_location_created_at_remove_location_upc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
    ]
