# Generated by Django 5.0 on 2023-12-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_media_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='uploaded_at',
        ),
    ]
