# Generated by Django 5.0 on 2023-12-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_media_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='product_id',
        ),
        migrations.AddField(
            model_name='media',
            name='upc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productinventory'),
        ),
    ]
