# Generated by Django 5.0 on 2023-12-17 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='format:Y-m-d H:M:S', verbose_name='created at'),
            preserve_default=False,
        ),
    ]
