# Generated by Django 5.0 on 2023-12-17 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_productattribute_producttype_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='format:required,unique,max-20', max_length=20, unique=True, verbose_name='stock keeping unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('location', models.CharField(max_length=20, verbose_name='location')),
            ],
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product_attribute',
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='attribute_values',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='attribute_values',
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalues',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributevalues',
            name='product_inventory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='web_id',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype', verbose_name='product type'),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(help_text='format:required,unique', max_length=50, null=True, unique=True, verbose_name='product upc'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='weight of product'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='inventory.product', verbose_name='product id'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_name', to='inventory.product', verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='product_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_type', to='inventory.producttype', verbose_name='product type'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='format:true=', verbose_name='Product visibility'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Category active'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='inventory.brand', to_field='name', verbose_name='brand name'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, verbose_name='recommended price'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, verbose_name='recommended price'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='upc',
            field=models.CharField(default=1, help_text='format:required,unique,max-12', max_length=12, unique=True, verbose_name='universal product code'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='weight',
            field=models.FloatField(default=0, verbose_name='product weight'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('url', models.URLField(max_length=100, verbose_name='url')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='media_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.media', verbose_name='pictures'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValues',
        ),
    ]
