# Generated by Django 5.0 on 2023-12-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_remove_productattributevalue_product_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='location',
        ),
    ]
