# Generated by Django 5.0 on 2023-12-18 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format:required,unique,max-255', max_length=30, unique=True, verbose_name='brand name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format:Y-m-d H:M:S', verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format:required,max-100', max_length=100, verbose_name='category name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Category active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='description')),
                ('url', models.URLField(max_length=100, verbose_name='url')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded at')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='format:required,unique,max-20', max_length=20, unique=True, verbose_name='stock keeping unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('location', models.CharField(max_length=20, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(help_text='format:required,unique', max_length=50, null=True, unique=True, verbose_name='product upc')),
                ('name', models.CharField(help_text='format:required,max-100', max_length=100, verbose_name='product name')),
                ('description', models.TextField(help_text='format:required,max-100', max_length=255, verbose_name='product description')),
                ('is_active', models.BooleanField(default=True, help_text='format:true=product visible', verbose_name='Product visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format:Y-m-d H:M:S', verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format:Y-m-d H:M:S', verbose_name='last update at')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='weight of product')),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand', verbose_name='brand')),
                ('media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.media', verbose_name='pictures')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format:product,unique,max-255', max_length=255, unique=True, verbose_name='type of product')),
                ('is_active', models.BooleanField(default=True, help_text='format:true=', verbose_name='Product visibility')),
                ('product_category_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.producttype', verbose_name='product type'),
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(default=1, help_text='format:required,unique,max-12', max_length=12, unique=True, verbose_name='universal product code')),
                ('is_active', models.BooleanField(default=True, help_text='format:true=product visible', verbose_name='product visibility')),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, verbose_name='recommended price')),
                ('store_price', models.DecimalField(decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, verbose_name='recommended price')),
                ('weight', models.FloatField(default=0, verbose_name='product weight')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format:Y-m-d H:M:S', verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='format:Y-m-d H:M:S', verbose_name='last update at')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('brand', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='inventory.brand', to_field='name', verbose_name='brand name')),
                ('product_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='inventory.product', verbose_name='product id')),
                ('product_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_name', to='inventory.product', verbose_name='product name')),
                ('product_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_type', to='inventory.producttype', verbose_name='product type')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
