# Generated by Django 5.0 on 2023-12-26 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='User name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, verbose_name='location')),
                ('is_active', models.BooleanField(default=True, help_text='format:true=product visible', verbose_name='Location availability')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='User name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('email', models.EmailField(max_length=20, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='product_category_id',
        ),
        migrations.AddField(
            model_name='media',
            name='upc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productinventory'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='brand_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='inventory.brand', verbose_name='brand id'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='media_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.media', verbose_name='pictures'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='inventory.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, null=True, verbose_name='recommended price'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='store_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, error_messages={'name': {'max_length': 'the price must be greater than or equal to 999.99'}}, help_text='format:maximum price 999.99', max_digits=5, null=True, verbose_name='recommended price'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
