# Generated by Django 5.0 on 2023-12-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_adminuser_location_user_remove_category_is_active_and_more'),
        ('inventory', '0013_remove_media_product_id_media_upc'),
    ]

    operations = [
    ]
