# Generated by Django 5.0 on 2023-12-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_20231226_1002'),
        ('inventory', '0014_merge_20231226_0958'),
    ]

    operations = [
    ]
