# Generated by Django 5.0 on 2023-12-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='name',
        ),
        migrations.AddField(
            model_name='profiles',
            name='full_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
