# Generated by Django 5.0 on 2023-12-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_profiles_city_alter_profiles_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='street_address',
            new_name='street',
        ),
    ]
