# Generated by Django 5.0 on 2023-12-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_shipping_address_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
